version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_DATA_DIR: /data/db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongoexpress:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongodb@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
volumes:
  mongo-data: