spring:
  application:
    name: Esports-Championship
  data:
    mongodb:
      uri: ${URI_MONGO}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: sa
esports:
  security:
    secret: ${MY_SECRET_KEY}
  cache:
    redis:
      time-to-live: 60000