spring:
  application:
    name: Esports-Championship
  data:
    mongodb:
      uri: mongodb://mongo:mongodb@localhost:27017/esports_championship?authSource=admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000